[package]

name = "png"
version = "0.1.0"
authors = ["The Servo Project Developers"]

links = "png-sys"
build = "build.rs"

[dependencies.png-sys]
path = "png-sys"

[dependencies]
libc = "0.1.5"

[build-dependencies.gcc]
git = "https://github.com/alexcrichton/gcc-rs"
